digraph "unitGraph" {
    "r15 := @parameter0: java.lang.String[]"
    "r16 = null"
    "$r0 = new java.net.Socket"
    "specialinvoke $r0.<java.net.Socket: void <init>(java.lang.String,int)>(\"localhost\", 5005)"
    "r16 = $r0"
    "staticinvoke <java.lang.Thread: void sleep(long)>(1000L)"
    "$r1 = new java.io.DataInputStream"
    "$r2 = virtualinvoke r16.<java.net.Socket: java.io.InputStream getInputStream()>()"
    "specialinvoke $r1.<java.io.DataInputStream: void <init>(java.io.InputStream)>($r2)"
    "r17 = $r1"
    "$r3 = <java.lang.System: java.io.PrintStream out>"
    "$r4 = virtualinvoke r17.<java.io.DataInputStream: java.lang.String readUTF()>()"
    "virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>($r4)"
    "goto [?= staticinvoke <java.lang.Thread: void sleep(long)>(1000L)]"
    "$r14 := @caughtexception"
    "r18 = $r14"
    "virtualinvoke r18.<java.io.IOException: void printStackTrace()>()"
    "r20 = new java.lang.NullPointerException"
    "specialinvoke r20.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")"
    "throw r20"
    "$r13 := @caughtexception"
    "virtualinvoke r16.<java.net.Socket: void close()>()"
    "goto [?= return]"
    "$r12 := @caughtexception"
    "$r11 := @caughtexception"
    "r19 = $r11"
    "virtualinvoke r19.<java.lang.InterruptedException: void printStackTrace()>()"
    "r21 = new java.lang.NullPointerException"
    "specialinvoke r21.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")"
    "throw r21"
    "$r10 := @caughtexception"
    "$r9 := @caughtexception"
    "$r8 := @caughtexception"
    "r6 = $r8"
    "r22 = new java.lang.NullPointerException"
    "specialinvoke r22.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")"
    "throw r22"
    "$r7 := @caughtexception"
    "goto [?= throw r6]"
    "$r5 := @caughtexception"
    "throw r6"
    "return"
    "r15 := @parameter0: java.lang.String[]"->"r16 = null";
    "r16 = null"->"$r14 := @caughtexception";
    "r16 = null"->"$r11 := @caughtexception";
    "r16 = null"->"$r8 := @caughtexception";
    "r16 = null"->"$r0 = new java.net.Socket";
    "$r0 = new java.net.Socket"->"$r14 := @caughtexception";
    "$r0 = new java.net.Socket"->"$r11 := @caughtexception";
    "$r0 = new java.net.Socket"->"$r8 := @caughtexception";
    "$r0 = new java.net.Socket"->"specialinvoke $r0.<java.net.Socket: void <init>(java.lang.String,int)>(\"localhost\", 5005)";
    "specialinvoke $r0.<java.net.Socket: void <init>(java.lang.String,int)>(\"localhost\", 5005)"->"$r14 := @caughtexception";
    "specialinvoke $r0.<java.net.Socket: void <init>(java.lang.String,int)>(\"localhost\", 5005)"->"$r11 := @caughtexception";
    "specialinvoke $r0.<java.net.Socket: void <init>(java.lang.String,int)>(\"localhost\", 5005)"->"$r8 := @caughtexception";
    "specialinvoke $r0.<java.net.Socket: void <init>(java.lang.String,int)>(\"localhost\", 5005)"->"r16 = $r0";
    "r16 = $r0"->"$r14 := @caughtexception";
    "r16 = $r0"->"$r11 := @caughtexception";
    "r16 = $r0"->"$r8 := @caughtexception";
    "r16 = $r0"->"staticinvoke <java.lang.Thread: void sleep(long)>(1000L)";
    "staticinvoke <java.lang.Thread: void sleep(long)>(1000L)"->"$r14 := @caughtexception";
    "staticinvoke <java.lang.Thread: void sleep(long)>(1000L)"->"$r11 := @caughtexception";
    "staticinvoke <java.lang.Thread: void sleep(long)>(1000L)"->"$r8 := @caughtexception";
    "staticinvoke <java.lang.Thread: void sleep(long)>(1000L)"->"$r1 = new java.io.DataInputStream";
    "$r1 = new java.io.DataInputStream"->"$r14 := @caughtexception";
    "$r1 = new java.io.DataInputStream"->"$r11 := @caughtexception";
    "$r1 = new java.io.DataInputStream"->"$r8 := @caughtexception";
    "$r1 = new java.io.DataInputStream"->"$r2 = virtualinvoke r16.<java.net.Socket: java.io.InputStream getInputStream()>()";
    "$r2 = virtualinvoke r16.<java.net.Socket: java.io.InputStream getInputStream()>()"->"$r14 := @caughtexception";
    "$r2 = virtualinvoke r16.<java.net.Socket: java.io.InputStream getInputStream()>()"->"$r11 := @caughtexception";
    "$r2 = virtualinvoke r16.<java.net.Socket: java.io.InputStream getInputStream()>()"->"$r8 := @caughtexception";
    "$r2 = virtualinvoke r16.<java.net.Socket: java.io.InputStream getInputStream()>()"->"specialinvoke $r1.<java.io.DataInputStream: void <init>(java.io.InputStream)>($r2)";
    "specialinvoke $r1.<java.io.DataInputStream: void <init>(java.io.InputStream)>($r2)"->"$r14 := @caughtexception";
    "specialinvoke $r1.<java.io.DataInputStream: void <init>(java.io.InputStream)>($r2)"->"$r11 := @caughtexception";
    "specialinvoke $r1.<java.io.DataInputStream: void <init>(java.io.InputStream)>($r2)"->"$r8 := @caughtexception";
    "specialinvoke $r1.<java.io.DataInputStream: void <init>(java.io.InputStream)>($r2)"->"r17 = $r1";
    "r17 = $r1"->"$r14 := @caughtexception";
    "r17 = $r1"->"$r11 := @caughtexception";
    "r17 = $r1"->"$r8 := @caughtexception";
    "r17 = $r1"->"$r3 = <java.lang.System: java.io.PrintStream out>";
    "$r3 = <java.lang.System: java.io.PrintStream out>"->"$r14 := @caughtexception";
    "$r3 = <java.lang.System: java.io.PrintStream out>"->"$r11 := @caughtexception";
    "$r3 = <java.lang.System: java.io.PrintStream out>"->"$r8 := @caughtexception";
    "$r3 = <java.lang.System: java.io.PrintStream out>"->"$r4 = virtualinvoke r17.<java.io.DataInputStream: java.lang.String readUTF()>()";
    "$r4 = virtualinvoke r17.<java.io.DataInputStream: java.lang.String readUTF()>()"->"$r14 := @caughtexception";
    "$r4 = virtualinvoke r17.<java.io.DataInputStream: java.lang.String readUTF()>()"->"$r11 := @caughtexception";
    "$r4 = virtualinvoke r17.<java.io.DataInputStream: java.lang.String readUTF()>()"->"$r8 := @caughtexception";
    "$r4 = virtualinvoke r17.<java.io.DataInputStream: java.lang.String readUTF()>()"->"virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>($r4)";
    "virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>($r4)"->"$r14 := @caughtexception";
    "virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>($r4)"->"$r11 := @caughtexception";
    "virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>($r4)"->"$r8 := @caughtexception";
    "virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>($r4)"->"goto [?= staticinvoke <java.lang.Thread: void sleep(long)>(1000L)]";
    "goto [?= staticinvoke <java.lang.Thread: void sleep(long)>(1000L)]"->"$r14 := @caughtexception";
    "goto [?= staticinvoke <java.lang.Thread: void sleep(long)>(1000L)]"->"$r11 := @caughtexception";
    "goto [?= staticinvoke <java.lang.Thread: void sleep(long)>(1000L)]"->"$r8 := @caughtexception";
    "goto [?= staticinvoke <java.lang.Thread: void sleep(long)>(1000L)]"->"staticinvoke <java.lang.Thread: void sleep(long)>(1000L)";
    "$r14 := @caughtexception"->"r18 = $r14";
    "$r14 := @caughtexception"->"$r8 := @caughtexception";
    "r18 = $r14"->"virtualinvoke r18.<java.io.IOException: void printStackTrace()>()";
    "r18 = $r14"->"$r8 := @caughtexception";
    "virtualinvoke r18.<java.io.IOException: void printStackTrace()>()"->"$r13 := @caughtexception";
    "virtualinvoke r18.<java.io.IOException: void printStackTrace()>()"->"$r8 := @caughtexception";
    "virtualinvoke r18.<java.io.IOException: void printStackTrace()>()"->"r20 = new java.lang.NullPointerException";
    "r20 = new java.lang.NullPointerException"->"specialinvoke r20.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")";
    "r20 = new java.lang.NullPointerException"->"$r13 := @caughtexception";
    "specialinvoke r20.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")"->"throw r20";
    "specialinvoke r20.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")"->"$r13 := @caughtexception";
    "throw r20"->"$r13 := @caughtexception";
    "$r13 := @caughtexception"->"virtualinvoke r16.<java.net.Socket: void close()>()";
    "$r13 := @caughtexception"->"$r12 := @caughtexception";
    "virtualinvoke r16.<java.net.Socket: void close()>()"->"goto [?= return]";
    "virtualinvoke r16.<java.net.Socket: void close()>()"->"$r12 := @caughtexception";
    "goto [?= return]"->"return";
    "$r12 := @caughtexception"->"goto [?= return]";
    "goto [?= return]"->"return";
    "$r11 := @caughtexception"->"r19 = $r11";
    "$r11 := @caughtexception"->"$r8 := @caughtexception";
    "r19 = $r11"->"virtualinvoke r19.<java.lang.InterruptedException: void printStackTrace()>()";
    "r19 = $r11"->"$r8 := @caughtexception";
    "virtualinvoke r19.<java.lang.InterruptedException: void printStackTrace()>()"->"$r10 := @caughtexception";
    "virtualinvoke r19.<java.lang.InterruptedException: void printStackTrace()>()"->"$r8 := @caughtexception";
    "virtualinvoke r19.<java.lang.InterruptedException: void printStackTrace()>()"->"r21 = new java.lang.NullPointerException";
    "r21 = new java.lang.NullPointerException"->"specialinvoke r21.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")";
    "r21 = new java.lang.NullPointerException"->"$r10 := @caughtexception";
    "specialinvoke r21.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")"->"throw r21";
    "specialinvoke r21.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")"->"$r10 := @caughtexception";
    "throw r21"->"$r10 := @caughtexception";
    "$r10 := @caughtexception"->"virtualinvoke r16.<java.net.Socket: void close()>()";
    "$r10 := @caughtexception"->"$r9 := @caughtexception";
    "virtualinvoke r16.<java.net.Socket: void close()>()"->"goto [?= return]";
    "virtualinvoke r16.<java.net.Socket: void close()>()"->"$r9 := @caughtexception";
    "goto [?= return]"->"return";
    "$r9 := @caughtexception"->"goto [?= return]";
    "goto [?= return]"->"return";
    "$r8 := @caughtexception"->"r6 = $r8";
    "$r8 := @caughtexception"->"$r8 := @caughtexception";
    "r6 = $r8"->"$r7 := @caughtexception";
    "r6 = $r8"->"$r8 := @caughtexception";
    "r6 = $r8"->"r22 = new java.lang.NullPointerException";
    "r22 = new java.lang.NullPointerException"->"specialinvoke r22.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")";
    "r22 = new java.lang.NullPointerException"->"$r7 := @caughtexception";
    "specialinvoke r22.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")"->"throw r22";
    "specialinvoke r22.<java.lang.NullPointerException: void <init>(java.lang.String)>(\"This statement would have triggered an Exception: virtualinvoke os.<java.io.DataOutputStream: void close()>()\")"->"$r7 := @caughtexception";
    "throw r22"->"$r7 := @caughtexception";
    "$r7 := @caughtexception"->"virtualinvoke r16.<java.net.Socket: void close()>()";
    "$r7 := @caughtexception"->"$r5 := @caughtexception";
    "virtualinvoke r16.<java.net.Socket: void close()>()"->"goto [?= throw r6]";
    "virtualinvoke r16.<java.net.Socket: void close()>()"->"$r5 := @caughtexception";
    "goto [?= throw r6]"->"throw r6";
    "$r5 := @caughtexception"->"throw r6";
}
