digraph "unitGraph" {
    "r43 = newarray (java.security.cert.Certificate)[0]"
    "$r0 = new java.security.KeyStore$PrivateKeyEntry"
    "specialinvoke $r0.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>(null, r43)"
    "r44 = $r0"
    "$r1 = new java.lang.SecurityException"
    "specialinvoke $r1.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 1 failed\")"
    "throw $r1"
    "$r38 := @caughtexception"
    "r45 = $r38"
    "$r39 = <java.lang.System: java.io.PrintStream out>"
    "virtualinvoke $r39.<java.io.PrintStream: void println(java.lang.String)>(\"test 1 passed\")"
    "$r40 = new java.security.KeyStore$PrivateKeyEntry"
    "$r41 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1"
    "specialinvoke $r41.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"
    "specialinvoke $r40.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r41, null)"
    "r46 = $r40"
    "$r42 = new java.lang.SecurityException"
    "specialinvoke $r42.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 2 failed\")"
    "throw $r42"
    "$r33 := @caughtexception"
    "r47 = $r33"
    "$r34 = <java.lang.System: java.io.PrintStream out>"
    "virtualinvoke $r34.<java.io.PrintStream: void println(java.lang.String)>(\"test 2 passed\")"
    "r48 = newarray (java.security.cert.Certificate)[0]"
    "$r35 = new java.security.KeyStore$PrivateKeyEntry"
    "$r36 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1"
    "specialinvoke $r36.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"
    "specialinvoke $r35.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r36, r48)"
    "r49 = $r35"
    "$r37 = new java.lang.SecurityException"
    "specialinvoke $r37.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 3 failed\")"
    "throw $r37"
    "$r26 := @caughtexception"
    "r50 = $r26"
    "$r27 = <java.lang.System: java.io.PrintStream out>"
    "virtualinvoke $r27.<java.io.PrintStream: void println(java.lang.String)>(\"test 3 passed\")"
    "r51 = newarray (java.security.cert.Certificate)[2]"
    "$r28 = new javaT.securityT.KeyStore.DefaultEntryType$Cert"
    "specialinvoke $r28.<javaT.securityT.KeyStore.DefaultEntryType$Cert: void <init>()>()"
    "r51[0] = $r28"
    "$r29 = new javaT.securityT.KeyStore.DefaultEntryType$X509Cert"
    "specialinvoke $r29.<javaT.securityT.KeyStore.DefaultEntryType$X509Cert: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"
    "r51[1] = $r29"
    "$r30 = new java.security.KeyStore$PrivateKeyEntry"
    "$r31 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1"
    "specialinvoke $r31.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"
    "specialinvoke $r30.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r31, r51)"
    "r52 = $r30"
    "$r32 = new java.lang.SecurityException"
    "specialinvoke $r32.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 4 failed\")"
    "throw $r32"
    "$r20 := @caughtexception"
    "r53 = $r20"
    "$r21 = <java.lang.System: java.io.PrintStream out>"
    "virtualinvoke $r21.<java.io.PrintStream: void println(java.lang.String)>(\"test 4 passed\")"
    "r54 = newarray (java.security.cert.Certificate)[1]"
    "$r22 = new javaT.securityT.KeyStore.DefaultEntryType$Cert"
    "specialinvoke $r22.<javaT.securityT.KeyStore.DefaultEntryType$Cert: void <init>()>()"
    "r54[0] = $r22"
    "$r23 = new java.security.KeyStore$PrivateKeyEntry"
    "$r24 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1"
    "specialinvoke $r24.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"
    "specialinvoke $r23.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r24, r54)"
    "r55 = $r23"
    "$r25 = new java.lang.SecurityException"
    "specialinvoke $r25.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 5 failed\")"
    "throw $r25"
    "$r2 := @caughtexception"
    "r56 = $r2"
    "$r3 = <java.lang.System: java.io.PrintStream out>"
    "virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>(\"test 5 passed\")"
    "r57 = newarray (java.security.cert.Certificate)[2]"
    "$r4 = new javaT.securityT.KeyStore.DefaultEntryType$X509Cert"
    "specialinvoke $r4.<javaT.securityT.KeyStore.DefaultEntryType$X509Cert: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"
    "r57[0] = $r4"
    "$r5 = new javaT.securityT.KeyStore.DefaultEntryType$X509Cert"
    "specialinvoke $r5.<javaT.securityT.KeyStore.DefaultEntryType$X509Cert: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"
    "r57[1] = $r5"
    "$r6 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1"
    "specialinvoke $r6.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"
    "r58 = $r6"
    "$r7 = new java.security.KeyStore$PrivateKeyEntry"
    "specialinvoke $r7.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>(r58, r57)"
    "r8 = $r7"
    "r9 = virtualinvoke r8.<java.security.KeyStore$PrivateKeyEntry: java.security.cert.Certificate[] getCertificateChain()>()"
    "$z0 = r9 instanceof java.security.cert.X509Certificate[]"
    "if $z0 == 0 goto $r10 = new java.lang.SecurityException"
    "$r11 = <java.lang.System: java.io.PrintStream out>"
    "virtualinvoke $r11.<java.io.PrintStream: void println(java.lang.String)>(\"test 6 passed\")"
    "goto [?= $i0 = lengthof r9]"
    "$r10 = new java.lang.SecurityException"
    "specialinvoke $r10.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 6 failed\")"
    "throw $r10"
    "$i0 = lengthof r9"
    "if $i0 != 2 goto $r59 = new java.lang.SecurityException"
    "$r13 = r9[0]"
    "$r12 = r57[0]"
    "if $r13 != $r12 goto $r59 = new java.lang.SecurityException"
    "$r15 = r9[1]"
    "$r14 = r57[1]"
    "if $r15 != $r14 goto $r59 = new java.lang.SecurityException"
    "$r16 = <java.lang.System: java.io.PrintStream out>"
    "virtualinvoke $r16.<java.io.PrintStream: void println(java.lang.String)>(\"test 7 passed\")"
    "goto [?= $r17 = virtualinvoke r8.<java.security.KeyStore$PrivateKeyEntry: java.security.PrivateKey getPrivateKey()>()]"
    "$r59 = new java.lang.SecurityException"
    "specialinvoke $r59.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 7 failed\")"
    "throw $r59"
    "$r17 = virtualinvoke r8.<java.security.KeyStore$PrivateKeyEntry: java.security.PrivateKey getPrivateKey()>()"
    "if $r17 != r58 goto $r18 = new java.lang.SecurityException"
    "$r19 = <java.lang.System: java.io.PrintStream out>"
    "virtualinvoke $r19.<java.io.PrintStream: void println(java.lang.String)>(\"test 8 passed\")"
    "goto [?= return]"
    "$r18 = new java.lang.SecurityException"
    "specialinvoke $r18.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 8 failed\")"
    "throw $r18"
    "return"
    "r43 = newarray (java.security.cert.Certificate)[0]"->"$r0 = new java.security.KeyStore$PrivateKeyEntry";
    "r43 = newarray (java.security.cert.Certificate)[0]"->"$r38 := @caughtexception";
    "$r0 = new java.security.KeyStore$PrivateKeyEntry"->"specialinvoke $r0.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>(null, r43)";
    "$r0 = new java.security.KeyStore$PrivateKeyEntry"->"$r38 := @caughtexception";
    "specialinvoke $r0.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>(null, r43)"->"r44 = $r0";
    "specialinvoke $r0.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>(null, r43)"->"$r38 := @caughtexception";
    "r44 = $r0"->"$r1 = new java.lang.SecurityException";
    "r44 = $r0"->"$r38 := @caughtexception";
    "$r1 = new java.lang.SecurityException"->"specialinvoke $r1.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 1 failed\")";
    "$r1 = new java.lang.SecurityException"->"$r38 := @caughtexception";
    "specialinvoke $r1.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 1 failed\")"->"throw $r1";
    "specialinvoke $r1.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 1 failed\")"->"$r38 := @caughtexception";
    "throw $r1"->"$r38 := @caughtexception";
    "$r38 := @caughtexception"->"r45 = $r38";
    "r45 = $r38"->"$r39 = <java.lang.System: java.io.PrintStream out>";
    "$r39 = <java.lang.System: java.io.PrintStream out>"->"virtualinvoke $r39.<java.io.PrintStream: void println(java.lang.String)>(\"test 1 passed\")";
    "virtualinvoke $r39.<java.io.PrintStream: void println(java.lang.String)>(\"test 1 passed\")"->"$r40 = new java.security.KeyStore$PrivateKeyEntry";
    "virtualinvoke $r39.<java.io.PrintStream: void println(java.lang.String)>(\"test 1 passed\")"->"$r33 := @caughtexception";
    "$r40 = new java.security.KeyStore$PrivateKeyEntry"->"$r41 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1";
    "$r40 = new java.security.KeyStore$PrivateKeyEntry"->"$r33 := @caughtexception";
    "$r41 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1"->"specialinvoke $r41.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)";
    "$r41 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1"->"$r33 := @caughtexception";
    "specialinvoke $r41.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"->"specialinvoke $r40.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r41, null)";
    "specialinvoke $r41.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"->"$r33 := @caughtexception";
    "specialinvoke $r40.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r41, null)"->"r46 = $r40";
    "specialinvoke $r40.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r41, null)"->"$r33 := @caughtexception";
    "r46 = $r40"->"$r42 = new java.lang.SecurityException";
    "r46 = $r40"->"$r33 := @caughtexception";
    "$r42 = new java.lang.SecurityException"->"specialinvoke $r42.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 2 failed\")";
    "$r42 = new java.lang.SecurityException"->"$r33 := @caughtexception";
    "specialinvoke $r42.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 2 failed\")"->"throw $r42";
    "specialinvoke $r42.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 2 failed\")"->"$r33 := @caughtexception";
    "throw $r42"->"$r33 := @caughtexception";
    "$r33 := @caughtexception"->"r47 = $r33";
    "r47 = $r33"->"$r34 = <java.lang.System: java.io.PrintStream out>";
    "$r34 = <java.lang.System: java.io.PrintStream out>"->"virtualinvoke $r34.<java.io.PrintStream: void println(java.lang.String)>(\"test 2 passed\")";
    "virtualinvoke $r34.<java.io.PrintStream: void println(java.lang.String)>(\"test 2 passed\")"->"r48 = newarray (java.security.cert.Certificate)[0]";
    "virtualinvoke $r34.<java.io.PrintStream: void println(java.lang.String)>(\"test 2 passed\")"->"$r26 := @caughtexception";
    "r48 = newarray (java.security.cert.Certificate)[0]"->"$r35 = new java.security.KeyStore$PrivateKeyEntry";
    "r48 = newarray (java.security.cert.Certificate)[0]"->"$r26 := @caughtexception";
    "$r35 = new java.security.KeyStore$PrivateKeyEntry"->"$r36 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1";
    "$r35 = new java.security.KeyStore$PrivateKeyEntry"->"$r26 := @caughtexception";
    "$r36 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1"->"specialinvoke $r36.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)";
    "$r36 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1"->"$r26 := @caughtexception";
    "specialinvoke $r36.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"->"specialinvoke $r35.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r36, r48)";
    "specialinvoke $r36.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"->"$r26 := @caughtexception";
    "specialinvoke $r35.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r36, r48)"->"r49 = $r35";
    "specialinvoke $r35.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r36, r48)"->"$r26 := @caughtexception";
    "r49 = $r35"->"$r37 = new java.lang.SecurityException";
    "r49 = $r35"->"$r26 := @caughtexception";
    "$r37 = new java.lang.SecurityException"->"specialinvoke $r37.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 3 failed\")";
    "$r37 = new java.lang.SecurityException"->"$r26 := @caughtexception";
    "specialinvoke $r37.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 3 failed\")"->"throw $r37";
    "specialinvoke $r37.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 3 failed\")"->"$r26 := @caughtexception";
    "throw $r37"->"$r26 := @caughtexception";
    "$r26 := @caughtexception"->"r50 = $r26";
    "r50 = $r26"->"$r27 = <java.lang.System: java.io.PrintStream out>";
    "$r27 = <java.lang.System: java.io.PrintStream out>"->"virtualinvoke $r27.<java.io.PrintStream: void println(java.lang.String)>(\"test 3 passed\")";
    "virtualinvoke $r27.<java.io.PrintStream: void println(java.lang.String)>(\"test 3 passed\")"->"r51 = newarray (java.security.cert.Certificate)[2]";
    "virtualinvoke $r27.<java.io.PrintStream: void println(java.lang.String)>(\"test 3 passed\")"->"$r20 := @caughtexception";
    "r51 = newarray (java.security.cert.Certificate)[2]"->"$r28 = new javaT.securityT.KeyStore.DefaultEntryType$Cert";
    "r51 = newarray (java.security.cert.Certificate)[2]"->"$r20 := @caughtexception";
    "$r28 = new javaT.securityT.KeyStore.DefaultEntryType$Cert"->"specialinvoke $r28.<javaT.securityT.KeyStore.DefaultEntryType$Cert: void <init>()>()";
    "$r28 = new javaT.securityT.KeyStore.DefaultEntryType$Cert"->"$r20 := @caughtexception";
    "specialinvoke $r28.<javaT.securityT.KeyStore.DefaultEntryType$Cert: void <init>()>()"->"r51[0] = $r28";
    "specialinvoke $r28.<javaT.securityT.KeyStore.DefaultEntryType$Cert: void <init>()>()"->"$r20 := @caughtexception";
    "r51[0] = $r28"->"$r29 = new javaT.securityT.KeyStore.DefaultEntryType$X509Cert";
    "r51[0] = $r28"->"$r20 := @caughtexception";
    "$r29 = new javaT.securityT.KeyStore.DefaultEntryType$X509Cert"->"specialinvoke $r29.<javaT.securityT.KeyStore.DefaultEntryType$X509Cert: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)";
    "$r29 = new javaT.securityT.KeyStore.DefaultEntryType$X509Cert"->"$r20 := @caughtexception";
    "specialinvoke $r29.<javaT.securityT.KeyStore.DefaultEntryType$X509Cert: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"->"r51[1] = $r29";
    "specialinvoke $r29.<javaT.securityT.KeyStore.DefaultEntryType$X509Cert: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"->"$r20 := @caughtexception";
    "r51[1] = $r29"->"$r30 = new java.security.KeyStore$PrivateKeyEntry";
    "r51[1] = $r29"->"$r20 := @caughtexception";
    "$r30 = new java.security.KeyStore$PrivateKeyEntry"->"$r31 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1";
    "$r30 = new java.security.KeyStore$PrivateKeyEntry"->"$r20 := @caughtexception";
    "$r31 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1"->"specialinvoke $r31.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)";
    "$r31 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1"->"$r20 := @caughtexception";
    "specialinvoke $r31.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"->"specialinvoke $r30.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r31, r51)";
    "specialinvoke $r31.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"->"$r20 := @caughtexception";
    "specialinvoke $r30.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r31, r51)"->"r52 = $r30";
    "specialinvoke $r30.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r31, r51)"->"$r20 := @caughtexception";
    "r52 = $r30"->"$r32 = new java.lang.SecurityException";
    "r52 = $r30"->"$r20 := @caughtexception";
    "$r32 = new java.lang.SecurityException"->"specialinvoke $r32.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 4 failed\")";
    "$r32 = new java.lang.SecurityException"->"$r20 := @caughtexception";
    "specialinvoke $r32.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 4 failed\")"->"throw $r32";
    "specialinvoke $r32.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 4 failed\")"->"$r20 := @caughtexception";
    "throw $r32"->"$r20 := @caughtexception";
    "$r20 := @caughtexception"->"r53 = $r20";
    "r53 = $r20"->"$r21 = <java.lang.System: java.io.PrintStream out>";
    "$r21 = <java.lang.System: java.io.PrintStream out>"->"virtualinvoke $r21.<java.io.PrintStream: void println(java.lang.String)>(\"test 4 passed\")";
    "virtualinvoke $r21.<java.io.PrintStream: void println(java.lang.String)>(\"test 4 passed\")"->"r54 = newarray (java.security.cert.Certificate)[1]";
    "virtualinvoke $r21.<java.io.PrintStream: void println(java.lang.String)>(\"test 4 passed\")"->"$r2 := @caughtexception";
    "r54 = newarray (java.security.cert.Certificate)[1]"->"$r22 = new javaT.securityT.KeyStore.DefaultEntryType$Cert";
    "r54 = newarray (java.security.cert.Certificate)[1]"->"$r2 := @caughtexception";
    "$r22 = new javaT.securityT.KeyStore.DefaultEntryType$Cert"->"specialinvoke $r22.<javaT.securityT.KeyStore.DefaultEntryType$Cert: void <init>()>()";
    "$r22 = new javaT.securityT.KeyStore.DefaultEntryType$Cert"->"$r2 := @caughtexception";
    "specialinvoke $r22.<javaT.securityT.KeyStore.DefaultEntryType$Cert: void <init>()>()"->"r54[0] = $r22";
    "specialinvoke $r22.<javaT.securityT.KeyStore.DefaultEntryType$Cert: void <init>()>()"->"$r2 := @caughtexception";
    "r54[0] = $r22"->"$r23 = new java.security.KeyStore$PrivateKeyEntry";
    "r54[0] = $r22"->"$r2 := @caughtexception";
    "$r23 = new java.security.KeyStore$PrivateKeyEntry"->"$r24 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1";
    "$r23 = new java.security.KeyStore$PrivateKeyEntry"->"$r2 := @caughtexception";
    "$r24 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1"->"specialinvoke $r24.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)";
    "$r24 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1"->"$r2 := @caughtexception";
    "specialinvoke $r24.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"->"specialinvoke $r23.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r24, r54)";
    "specialinvoke $r24.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"->"$r2 := @caughtexception";
    "specialinvoke $r23.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r24, r54)"->"r55 = $r23";
    "specialinvoke $r23.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>($r24, r54)"->"$r2 := @caughtexception";
    "r55 = $r23"->"$r25 = new java.lang.SecurityException";
    "r55 = $r23"->"$r2 := @caughtexception";
    "$r25 = new java.lang.SecurityException"->"specialinvoke $r25.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 5 failed\")";
    "$r25 = new java.lang.SecurityException"->"$r2 := @caughtexception";
    "specialinvoke $r25.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 5 failed\")"->"throw $r25";
    "specialinvoke $r25.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 5 failed\")"->"$r2 := @caughtexception";
    "throw $r25"->"$r2 := @caughtexception";
    "$r2 := @caughtexception"->"r56 = $r2";
    "r56 = $r2"->"$r3 = <java.lang.System: java.io.PrintStream out>";
    "$r3 = <java.lang.System: java.io.PrintStream out>"->"virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>(\"test 5 passed\")";
    "virtualinvoke $r3.<java.io.PrintStream: void println(java.lang.String)>(\"test 5 passed\")"->"r57 = newarray (java.security.cert.Certificate)[2]";
    "r57 = newarray (java.security.cert.Certificate)[2]"->"$r4 = new javaT.securityT.KeyStore.DefaultEntryType$X509Cert";
    "$r4 = new javaT.securityT.KeyStore.DefaultEntryType$X509Cert"->"specialinvoke $r4.<javaT.securityT.KeyStore.DefaultEntryType$X509Cert: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)";
    "specialinvoke $r4.<javaT.securityT.KeyStore.DefaultEntryType$X509Cert: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"->"r57[0] = $r4";
    "r57[0] = $r4"->"$r5 = new javaT.securityT.KeyStore.DefaultEntryType$X509Cert";
    "$r5 = new javaT.securityT.KeyStore.DefaultEntryType$X509Cert"->"specialinvoke $r5.<javaT.securityT.KeyStore.DefaultEntryType$X509Cert: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)";
    "specialinvoke $r5.<javaT.securityT.KeyStore.DefaultEntryType$X509Cert: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"->"r57[1] = $r5";
    "r57[1] = $r5"->"$r6 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1";
    "$r6 = new javaT.securityT.KeyStore.DefaultEntryType$PrivKey1"->"specialinvoke $r6.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)";
    "specialinvoke $r6.<javaT.securityT.KeyStore.DefaultEntryType$PrivKey1: void <init>(javaT.securityT.KeyStore.DefaultEntryType$1)>(null)"->"r58 = $r6";
    "r58 = $r6"->"$r7 = new java.security.KeyStore$PrivateKeyEntry";
    "$r7 = new java.security.KeyStore$PrivateKeyEntry"->"specialinvoke $r7.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>(r58, r57)";
    "specialinvoke $r7.<java.security.KeyStore$PrivateKeyEntry: void <init>(java.security.PrivateKey,java.security.cert.Certificate[])>(r58, r57)"->"r8 = $r7";
    "r8 = $r7"->"r9 = virtualinvoke r8.<java.security.KeyStore$PrivateKeyEntry: java.security.cert.Certificate[] getCertificateChain()>()";
    "r9 = virtualinvoke r8.<java.security.KeyStore$PrivateKeyEntry: java.security.cert.Certificate[] getCertificateChain()>()"->"$z0 = r9 instanceof java.security.cert.X509Certificate[]";
    "$z0 = r9 instanceof java.security.cert.X509Certificate[]"->"if $z0 == 0 goto $r10 = new java.lang.SecurityException";
    "if $z0 == 0 goto $r10 = new java.lang.SecurityException"->"$r11 = <java.lang.System: java.io.PrintStream out>";
    "if $z0 == 0 goto $r10 = new java.lang.SecurityException"->"$r10 = new java.lang.SecurityException";
    "$r11 = <java.lang.System: java.io.PrintStream out>"->"virtualinvoke $r11.<java.io.PrintStream: void println(java.lang.String)>(\"test 6 passed\")";
    "virtualinvoke $r11.<java.io.PrintStream: void println(java.lang.String)>(\"test 6 passed\")"->"goto [?= $i0 = lengthof r9]";
    "goto [?= $i0 = lengthof r9]"->"$i0 = lengthof r9";
    "$r10 = new java.lang.SecurityException"->"specialinvoke $r10.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 6 failed\")";
    "specialinvoke $r10.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 6 failed\")"->"throw $r10";
    "$i0 = lengthof r9"->"if $i0 != 2 goto $r59 = new java.lang.SecurityException";
    "if $i0 != 2 goto $r59 = new java.lang.SecurityException"->"$r13 = r9[0]";
    "if $i0 != 2 goto $r59 = new java.lang.SecurityException"->"$r59 = new java.lang.SecurityException";
    "$r13 = r9[0]"->"$r12 = r57[0]";
    "$r12 = r57[0]"->"if $r13 != $r12 goto $r59 = new java.lang.SecurityException";
    "if $r13 != $r12 goto $r59 = new java.lang.SecurityException"->"$r15 = r9[1]";
    "if $r13 != $r12 goto $r59 = new java.lang.SecurityException"->"$r59 = new java.lang.SecurityException";
    "$r15 = r9[1]"->"$r14 = r57[1]";
    "$r14 = r57[1]"->"if $r15 != $r14 goto $r59 = new java.lang.SecurityException";
    "if $r15 != $r14 goto $r59 = new java.lang.SecurityException"->"$r16 = <java.lang.System: java.io.PrintStream out>";
    "if $r15 != $r14 goto $r59 = new java.lang.SecurityException"->"$r59 = new java.lang.SecurityException";
    "$r16 = <java.lang.System: java.io.PrintStream out>"->"virtualinvoke $r16.<java.io.PrintStream: void println(java.lang.String)>(\"test 7 passed\")";
    "virtualinvoke $r16.<java.io.PrintStream: void println(java.lang.String)>(\"test 7 passed\")"->"goto [?= $r17 = virtualinvoke r8.<java.security.KeyStore$PrivateKeyEntry: java.security.PrivateKey getPrivateKey()>()]";
    "goto [?= $r17 = virtualinvoke r8.<java.security.KeyStore$PrivateKeyEntry: java.security.PrivateKey getPrivateKey()>()]"->"$r17 = virtualinvoke r8.<java.security.KeyStore$PrivateKeyEntry: java.security.PrivateKey getPrivateKey()>()";
    "$r59 = new java.lang.SecurityException"->"specialinvoke $r59.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 7 failed\")";
    "specialinvoke $r59.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 7 failed\")"->"throw $r59";
    "$r17 = virtualinvoke r8.<java.security.KeyStore$PrivateKeyEntry: java.security.PrivateKey getPrivateKey()>()"->"if $r17 != r58 goto $r18 = new java.lang.SecurityException";
    "if $r17 != r58 goto $r18 = new java.lang.SecurityException"->"$r19 = <java.lang.System: java.io.PrintStream out>";
    "if $r17 != r58 goto $r18 = new java.lang.SecurityException"->"$r18 = new java.lang.SecurityException";
    "$r19 = <java.lang.System: java.io.PrintStream out>"->"virtualinvoke $r19.<java.io.PrintStream: void println(java.lang.String)>(\"test 8 passed\")";
    "virtualinvoke $r19.<java.io.PrintStream: void println(java.lang.String)>(\"test 8 passed\")"->"goto [?= return]";
    "goto [?= return]"->"return";
    "$r18 = new java.lang.SecurityException"->"specialinvoke $r18.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 8 failed\")";
    "specialinvoke $r18.<java.lang.SecurityException: void <init>(java.lang.String)>(\"test 8 failed\")"->"throw $r18";
}
